name: E2E tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: corepack enable
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Activate pinned pnpm
        run: corepack enable && corepack prepare pnpm@9.11.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm build

      - name: Upload app build
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: app-dist
          path: dist
          if-no-files-found: error
          retention-days: 1

  test:
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - run: corepack enable

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Activate pinned pnpm
        run: corepack enable && corepack prepare pnpm@9.11.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download app build
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: app-dist
          path: dist

      - name: Restore Playwright browsers from cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('playwright.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm run test:e2e --shard=${{ matrix.shard }}
