name: Release new versions

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - run: corepack enable

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Activate pinned pnpm
        run: corepack enable && corepack prepare pnpm@9.11.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the app
        run: pnpm build

      - name: Zip the app
        run: zip -r it-tools-${{ env.RELEASE_VERSION }}.zip dist/*

      - name: Get changelog
        id: changelog
        run: |
          EOF=$(openssl rand -hex 8)
          echo "changelog<<$EOF" >> $GITHUB_OUTPUT
          node ./scripts/getLatestChangelog.mjs >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: it-tools-${{ env.RELEASE_VERSION }}.zip
          tag_name: v${{ env.RELEASE_VERSION }}
          draft: true
          prerelease: false
          body: |
            ## Changelog

            ${{ steps.changelog.outputs.changelog }}
